import {setSafeHTML} from './security.js';
import {date,empty,esc,get,panel,prob,num,pct} from './analysis-components.js';
const titles={abnormal_return:'Unusual price movement',unusual_volume:'Unusual trading volume',volume_change:'Unusual change in volume',volatility_spike:'Elevated price fluctuations'};
function card(a){const c=a.context||{},rank=c.percentile;
 return `<article class="card"><header><div><h3>${esc(a.symbol)} · ${esc(titles[a.type]||a.type)}</h3><p>${date(a.timestamp)}</p></div><span class="badge ${a.severity}">${rank==null?esc(a.severity):rank>99?'Highly unusual':rank>95?'Unusual':'Mildly unusual'}</span></header><strong>${rank==null?'Percentile unavailable':`${num(rank,1)}th percentile`}</strong><p>${rank==null?'Recalculate this event to attach reference-distribution metadata.':`More unusual than approximately ${num(rank,1)}% of ${c.reference_observations} scored observations for this asset.`}</p><div class="severity-bar"><span style="width:${Math.max(0,Math.min(100,rank??0))}%"></span></div><h4>What was observed?</h4><ul><li>Daily price change: ${pct(c.return_1d)}</li><li>Trading volume: ${num(c.relative_volume_20)}× the 20-session average</li><li>Annualised volatility: ${prob(c.volatility_20)}</li></ul><details class="details"><summary>Technical score & reference history</summary><p>Ensemble rank score: ${num(a.score,4)}. Isolation Forest: ${num(c.isolation_raw,4)}. LOF: ${num(c.lof_raw,4)}.</p><p>${date(c.reference_start)} – ${date(c.reference_end)}</p><p>${esc(c.scoring_method||'Legacy retrospective detector output.')}</p></details></article>`;
}
export async function anomalies(){const assets=await get('/assets');return `${panel('Investigate unusual market activity','Percentiles compare events with all scored observations for that asset. High ranks are expected among flagged events.',`<div class="toolbar"><div class="field"><label for="anomalySymbol">Asset</label><select id="anomalySymbol"><option value="">All assets</option>${assets.map(a=>`<option value="${esc(a.symbol)}">${esc(a.symbol)} · ${esc(a.name)}</option>`).join('')}</select></div><div class="field"><label for="anomalyType">Type</label><select id="anomalyType"><option value="">All types</option></select></div><div class="field"><label for="anomalyWindow">Observation window</label><select id="anomalyWindow"><option value="90">Latest 90 calendar days</option><option value="365">Latest year</option><option value="all">All stored history</option></select></div></div>`)}<div id="anomalySummary" class="mt"></div><div id="anomalyResults" class="mt"></div>`}
export async function hydrateAnomalies(){let request=0;const draw=async()=>{const version=++request,s=document.querySelector('#anomalySymbol').value,type=document.querySelector('#anomalyType').value,window=document.querySelector('#anomalyWindow').value;const all=await get(`/anomalies?limit=5000${s?'&symbol='+encodeURIComponent(s):''}`);if(version!==request||!document.querySelector('#anomalyResults'))return;
 const types=[...new Set(all.map(a=>a.type))];setSafeHTML(document.querySelector('#anomalyType'),'<option value="">All types</option>'+types.map(t=>`<option value="${esc(t)}" ${t===type?'selected':''}>${esc(titles[t]||t)}</option>`).join(''));
 const latest=all.length?Math.max(...all.map(a=>Date.parse(a.timestamp))):0,cutoff=window==='all'?-Infinity:latest-Number(window)*86400000;
 const rows=all.filter(a=>(!type||a.type===type)&&Date.parse(a.timestamp)>=cutoff),high=rows.filter(a=>a.severity==='high').length,medium=rows.filter(a=>a.severity==='medium').length,affected=new Set(rows.map(a=>a.symbol));
 const most=rows.slice().sort((a,b)=>((b.context?.percentile)||0)-((a.context?.percentile)||0))[0];
 setSafeHTML(document.querySelector('#anomalySummary'),`<div class="grid metrics"><article class="card metric"><span>Events in selected window</span><strong>${rows.length}</strong></article><article class="card metric"><span>Severity counts</span><strong>${high} high</strong><small>${medium} medium · ${rows.length-high-medium} low</small></article><article class="card metric"><span>Assets affected</span><strong>${affected.size}</strong></article><article class="card metric"><span>Most unusual in window</span><strong>${esc(most?.symbol||'None')}</strong><small>${most?.context?.percentile!=null?num(most.context.percentile,1)+'th percentile':''}</small></article></div><p class="chart-caption">Window ends at the latest stored flagged event, ${latest?date(latest):'unavailable'}. Up to 5,000 events are retrieved; newest 90 matching cards are displayed. These retrospective scores are not live alerts.</p>`);
 setSafeHTML(document.querySelector('#anomalyResults'),rows.length?`<section class="grid three">${rows.slice(0,90).map(card).join('')}</section>`:empty('No flagged observations match this asset, type and date window.'));
 };for(const id of ['anomalySymbol','anomalyType','anomalyWindow'])document.getElementById(id).addEventListener('change',draw);await draw();}
