import {api} from './api.js'; import {connectMarket} from './websocket.js'; import {views,hydrators} from './views.js';
import {setSafeHTML} from './security.js';
const workspace=document.querySelector('#workspace'),title=document.querySelector('#pageTitle'),freshness=document.querySelector('#freshness');
let routeVersion=0;
const names={overview:'Overview',market:'Market',stock:'Stock Intelligence',predictions:'AI Predictions',regimes:'Market Regimes',news:'News Intelligence',anomalies:'Anomaly Center',explainability:'Explainability',backtesting:'Backtest Lab',research:'Research Lab'};
function setFresh(x){const s=(x?.status||'UNAVAILABLE').toUpperCase();freshness.textContent=s.replace('_',' ');freshness.className=`status ${s.toLowerCase()}`;freshness.title=x?.as_of?`As of ${new Date(x.as_of).toLocaleString('en-IN')}`:'No market observation loaded'}
function showToast(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2500)}
async function route(){const version=++routeVersion;const page=(location.hash.slice(1)||'overview').split('?')[0];const view=views[page]||views.overview;title.textContent=names[page]||names.overview;document.querySelectorAll('#nav a').forEach(a=>{const active=a.dataset.page===page;a.classList.toggle('active',active);active?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current')});setSafeHTML(workspace,'<div class="skeleton-grid"><i></i><i></i><i></i><i></i></div>');try{const html=await view();if(version!==routeVersion)return;setSafeHTML(workspace,html);await hydrators[page]?.()}catch(e){if(version===routeVersion)setSafeHTML(workspace,`<div class="empty"><div><b>This view is unavailable</b><span>${e.message}</span></div></div>`)}const sidebar=document.querySelector('.sidebar');sidebar.classList.remove('open');document.querySelector('#menuButton').setAttribute('aria-expanded','false')}
window.addEventListener('hashchange',route);document.querySelector('#menuButton').addEventListener('click',e=>{const open=document.querySelector('.sidebar').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.sidebar').classList.remove('open');document.querySelector('#menuButton').setAttribute('aria-expanded','false')}});document.querySelector('#globalSearch').addEventListener('keydown',async e=>{if(e.key!=='Enter'||!e.target.value.trim())return;const query=e.target.value.trim().toUpperCase();try{const assets=await api.assets();const match=assets.find(a=>a.asset_type==='stock'&&(a.symbol===query||a.name.toUpperCase().includes(query)));if(!match){showToast('No matching stock in the configured universe');return}location.hash='stock';setTimeout(()=>{const s=document.querySelector('#stockSymbol');if(s){s.value=match.symbol;s.dispatchEvent(new Event('change'))}},100)}catch{showToast('Asset search is temporarily unavailable')}});connectMarket(d=>setFresh(d.freshness),state=>{if(state==='reconnecting'||state==='unavailable')setFresh({status:'UNAVAILABLE'})});api.overview().then(d=>setFresh(d.freshness)).catch(()=>setFresh(null));route();
