import {api} from './api.js';
import {connectMarket} from './websocket.js';
import {coreViews as views,coreHydrators as hydrators} from './core-pages.js';
import {setSafeHTML} from './security.js';

const workspace=document.querySelector('#workspace'),title=document.querySelector('#pageTitle'),subtitle=document.querySelector('#pageSubtitle'),freshness=document.querySelector('#freshness'),marketMessage=document.querySelector('#marketMessage'),nav=document.querySelector('#nav');
let routeVersion=0;
const pages={overview:['Overview','Real Indian-market snapshot.'],market:['Market Explore','Search real tracked market data.'],stock:['Stock Intelligence','Understand observed stock behavior.'],predictions:['AI Predictions','Experimental outlook and estimates from real market history.']};
function setFresh(x){const s=(x?.status||'UNAVAILABLE').toUpperCase();freshness.textContent=s.replace('_',' ');freshness.className=`status ${s.toLowerCase()}`;freshness.title=x?.as_of?`Latest observation: ${new Date(x.as_of).toLocaleString('en-IN')}`:'No market observation loaded';marketMessage.textContent=s==='STALE'?`Stored prices are stale (last observation ${x?.as_of?new Date(x.as_of).toLocaleDateString('en-IN'):'unknown'}). Use Get latest data to check for newer provider observations.`:s==='MARKET_CLOSED'?'Indian markets are currently closed. Latest available observations are shown.':s==='LIVE'?'Latest available market observations are shown.':s==='DELAYED'?'Delayed market observations are shown.':'Market freshness is currently unavailable.'}
function showToast(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
async function route(){const version=++routeVersion,requested=(location.hash.slice(1)||'overview').split('?')[0],page=pages[requested]?requested:'overview',view=views[page],meta=pages[page];title.textContent=meta[0];subtitle.textContent=meta[1];document.querySelectorAll('#nav a').forEach(a=>{const active=a.dataset.page===page;a.classList.toggle('active',active);active?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current')});setSafeHTML(workspace,'<div class="skeleton-grid" aria-label="Loading controls"><i></i><i></i><i></i><i></i></div>');try{const html=await view();if(version!==routeVersion)return;setSafeHTML(workspace,html);await hydrators[page]?.()}catch(e){if(version===routeVersion)setSafeHTML(workspace,`<div class="empty"><div><b>We couldn’t load this view</b><span>Please try again. Technical detail: ${e.message}</span></div></div>`)}nav.classList.remove('open');document.querySelector('#menuButton').setAttribute('aria-expanded','false');workspace.focus({preventScroll:true})}
window.addEventListener('hashchange',route);
document.querySelector('#menuButton').addEventListener('click',e=>{const open=nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');document.querySelector('#menuButton').setAttribute('aria-expanded','false')}});
document.querySelector('#globalSearch').addEventListener('keydown',async e=>{if(e.key!=='Enter'||!e.target.value.trim())return;const query=e.target.value.trim().toUpperCase();try{const assets=await api.assets();const match=assets.find(a=>a.symbol===query||a.name.toUpperCase().includes(query));if(!match){showToast('No matching company or index is in the tracked universe.');return}location.hash=`${match.asset_type==='stock'?'stock':'market'}?symbol=${match.symbol}`}catch{showToast('Asset search is temporarily unavailable.')}});
connectMarket(d=>setFresh(d.freshness),state=>{if(state==='reconnecting'||state==='unavailable')setFresh({status:'UNAVAILABLE'})});
api.overview().then(d=>setFresh(d.freshness)).catch(()=>setFresh(null));
route();
