import {setSafeHTML} from './security.js';
import {date,empty,esc,get,panel,pct,table} from './analysis-components.js';
const colors=['#6dafff','#e9b95f','#aa92ff','#36d49a'];
function observation(p){return table(['Average daily return','Annualised volatility','10-session momentum','Mean decline from recent peak','Trading observations'],[[pct(p.average_return),pct(p.volatility),pct(p.momentum),pct(p.drawdown),p.observations]])}
export async function regimes(){
 const r=await get('/regimes/summary');if(!r.current)return empty('Market environment history has not been calculated.');
 const c=r.current,total=r.periods.reduce((sum,p)=>sum+p.observations,0);
 return `<article class="hero-summary"><span class="eyebrow">Current observed market environment</span><h3>${esc(c.name)}</h3><p>${c.momentum<0?'Recent momentum has been negative.':'Recent momentum has been positive.'} ${c.volatility>.20?'Daily price fluctuations have been relatively large.':'Price fluctuations have been lower or moderate.'} The current assigned period has lasted ${c.observations} trading observations, since ${date(c.start)}.</p><p class="mt">This describes the available market history. It does not establish that prices will continue in the same direction.</p></article>
 ${panel('What are we observing?','Statistics for the current contiguous period; volatility is annualised.',observation(c))}
 ${panel('Market environment timeline','Each coloured segment is a category. Width represents the number of observed trading sessions, not the numeric state ID.',`<div class="environment-legend">${r.environments.map(e=>`<span><i style="background:${colors[e.state%4]}"></i>${esc(e.name)}</span>`).join('')}</div><div class="environment-timeline" role="group" aria-label="Categorical market environment periods">${r.periods.map((p,i)=>`<button class="environment-period" data-period="${i}" style="flex-grow:${p.observations};background:${colors[p.state%4]}" title="${esc(p.name)}: ${date(p.start)} to ${date(p.end)}; ${p.observations} observations" aria-label="${esc(p.name)}, ${date(p.start)} to ${date(p.end)}"></button>`).join('')}</div><div class="timeline-dates"><span>${date(r.periods[0].start)}</span><span>${total} sessions</span><span>${date(c.end)}</span></div><div id="periodDetail" class="mt"><p>Select any period to inspect its dates and measured characteristics.</p></div>`)}
 ${panel('Discovered environments','Names are derived from measured return, volatility and momentum.',r.environments.map(e=>`<details class="details"><summary>${esc(e.name)} · ${e.observations} observations</summary>${observation(e)}<p>Technical state ID: ${e.state}</p></details>`).join(''))}
 ${panel('How the environment changed','These compare averages of adjacent completed or current periods. They describe the data; they do not prove why a transition occurred.',r.transitions.map(t=>`<article class="transition-event"><time>${date(t.date)}</time><h4>${esc(t.from)} → ${esc(t.to)}</h4><p>Daily-return change ${pct(t.return_change)} · annualised-volatility change ${pct(t.volatility_change)} · momentum change ${pct(t.momentum_change)} · average-decline change ${pct(t.drawdown_change)}</p></article>`).join(''))}
 <details class="card details mt"><summary>Method, thresholds and limitations</summary><p>${esc(r.interpretation)}</p><p>${esc(r.thresholds)}</p></details>`;
}
export async function hydrateRegimes(){const r=await get('/regimes/summary');document.querySelectorAll('[data-period]').forEach(button=>button.addEventListener('click',()=>{const p=r.periods[Number(button.dataset.period)];setSafeHTML(document.querySelector('#periodDetail'),`<h4>${esc(p.name)}</h4><p>${date(p.start)} to ${date(p.end)}</p>${observation(p)}`)}))}
