import {prettyFeature} from './terminology.js';
import {setSafeHTML} from './security.js';
import {date,empty,esc,failure,get,metricCells,metricHeaders,modelName,num,panel,prob,table} from './analysis-components.js';

const shortGroup=name=>name.replaceAll('technical_market_regime_volume','Technical + market + environment + volume').replaceAll('technical_market_regime','Technical + market + environment').replaceAll('technical_market','Technical + market').replaceAll('technical','Technical only');
const confusion=metrics=>table(['Actual / predicted','DOWN','UP'],[['DOWN',...metrics.confusion_matrix[0]],['UP',...metrics.confusion_matrix[1]]]);

export async function research(){
 try{
  const r=await get('/research/synthetic'),s=r.selected,d=r.dataset;
  return `<div class="hero-summary"><span class="eyebrow">Prediction research dataset · controlled synthetic market-like data</span><h3>Research model accuracy: ${prob(s.test.accuracy)}</h3><p><b>This result is not a claim about predicting real Indian stocks.</b> ${esc(d.disclaimer)}</p><p class="mt">${d.observations.toLocaleString()} observations · ${d.assets} synthetic assets · ${d.sectors} sectors · ${esc(d.date_range.start)} to ${esc(d.date_range.end)}. ${r.artifact?.loaded?'Selected research artifact verified by the API.':'Model artifact unavailable.'}</p></div>
  ${panel('Research model performance','All figures below are actual final-test measurements on the controlled dataset. Parameters, horizon and feature group were selected using the earlier validation period only.',table(['Model',...metricHeaders()],r.model_results.map(x=>[modelName(x.model)+(x.model===s.model?' · selected':''),...metricCells(x.test)])))}
  ${panel('What is being predicted?',`The selected model uses ${shortGroup(s.feature_group).toLowerCase()} inputs for a ${r.target.horizon_sessions}-trading-day direction target.`, `<div class="kpi-strip"><div><small>UP observations</small><b>${prob(d.class_distribution.up)}</b></div><div><small>DOWN observations</small><b>${prob(d.class_distribution.down)}</b></div><div><small>Majority baseline</small><b>${prob(d.majority_accuracy)}</b></div><div><small>Final-test observations</small><b>${s.test.n.toLocaleString()}</b></div></div><p class="chart-caption">${esc(r.target.definition)} Class balance is reported so raw accuracy is not mistaken for a majority-class shortcut.</p>`)}
  ${panel('Selected-model confusion matrix','Rows are actual controlled future directions; columns are model predictions.',`${confusion(s.test)}<p>Balanced accuracy ${prob(s.test.balanced_accuracy)} · ROC-AUC ${num(s.test.roc_auc,3)} · MCC ${num(s.test.mcc,3)}.</p>`)}
  ${panel('Feature selection','Feature groups were compared against the validation set without using the final test.',table(['Feature group','Validation class-balanced accuracy'],r.feature_group_experiments.map(x=>[shortGroup(x.feature_group),prob(x.validation.balanced_accuracy)])))}
  ${panel('Target-horizon experiment','One-, three- and five-session forward directions were compared chronologically. The selected horizon is shown everywhere on this page.',table(['Target horizon','Validation UP share','Validation accuracy','Validation class-balanced accuracy','Validation ROC-AUC'],r.horizon_experiments.map(x=>[`${x.horizon} trading ${x.horizon===1?'day':'days'}`,prob(x.class_distribution),prob(x.validation.accuracy),prob(x.validation.balanced_accuracy),num(x.validation.roc_auc,3)])))}
  ${panel('What influenced the selected model?','Mean absolute SHAP contribution is calculated from refit train-and-validation observations only, not final-test rows. It is not a causal explanation.',r.shap_feature_importance?.[0]?.unavailable?`<p class="notice warning">SHAP was unavailable: ${esc(r.shap_feature_importance[0].unavailable)}</p>`:table(['Input','Mean |SHAP|'],r.shap_feature_importance.slice(0,10).map(x=>[esc(prettyFeature(x.feature)),num(x.mean_absolute_shap,4)])))}
  ${panel('Performance by synthetic asset','Every listed result is on the chronological final test period. Search or sort to inspect consistency rather than relying on an aggregate score.',`<div class="table-tools"><input id="researchAsset" type="search" aria-label="Search synthetic asset performance" placeholder="Search synthetic asset"><select id="assetSort" aria-label="Sort synthetic performance"><option value="symbol">Symbol A–Z</option><option value="accuracy">Accuracy: high to low</option><option value="f1">F1: high to low</option></select></div><div id="assetPerformance"></div>`)}
  ${panel('Performance by controlled market environment','Environment is a current, persistent feature in the synthetic generator—not a future-derived label.',table(['Environment','Observations',...metricHeaders()],r.environment_results.map(x=>[esc(x.environment.replaceAll('_',' ')),x.n.toLocaleString(),...metricCells(x.metrics)])))}
  ${panel('Chronological methodology','The data is synthetic by design, but its evaluation is still time-aware and leakage-controlled.',`<p>${esc(r.methodology)}</p><p>Train ended ${date(r.split.train_end)}; validation ran ${date(r.split.validation_start)} to ${date(r.split.validation_end)}; the untouched final test ran ${date(r.split.test_start)} to ${date(r.split.test_end)}.</p><p class="notice warning">Real Indian-market charts, regimes, anomalies, and historical performance remain based on real provider data. Their real-market prediction baseline is deliberately not replaced with this controlled-dataset result.</p>`)}
  <details class="details card mt"><summary>Selected model configuration</summary><pre>${esc(JSON.stringify({model:s.model,feature_group:s.feature_group,parameters:s.parameters,validation:s.validation,test:s.test},null,2))}</pre></details>`;
 }catch(error){return failure(error)}
}

export async function hydrateResearch(){
 try{
  const r=await get('/research/synthetic');
  const render=()=>{const search=document.querySelector('#researchAsset').value.toUpperCase(),sort=document.querySelector('#assetSort').value;const rows=r.asset_results.filter(x=>x.symbol.includes(search)).sort((a,b)=>sort==='symbol'?a.symbol.localeCompare(b.symbol):b.metrics[sort]-a.metrics[sort]);setSafeHTML(document.querySelector('#assetPerformance'),table(['Asset','Sector','Observations',...metricHeaders()],rows.map(x=>[esc(x.symbol),esc(x.sector),x.n.toLocaleString(),...metricCells(x.metrics)])))};
  document.querySelector('#researchAsset')?.addEventListener('input',render);document.querySelector('#assetSort')?.addEventListener('change',render);render();
 }catch(error){const target=document.querySelector('#assetPerformance');if(target)setSafeHTML(target,empty(error.message))}
}
