import {lineChart} from './charts.js';
import {prettyFeature} from './terminology.js';
import {setSafeHTML} from './security.js';
import {date,empty,esc,get,metricHeaders,metricCells,modelName,panel,prob,num,table} from './analysis-components.js';

export async function research(){
 const r=await get('/research/experiments'),s=r.selected;
 if(!s)return empty('The experiment matrix is still running.');
 const winner=r.experiments.find(e=>e.configuration===s.configuration&&e.feature_set===s.feature_set&&e.horizon===1&&e.calibration===s.calibration);
 const models=[...new Set(r.experiments.map(e=>e.model))].map(model=>r.experiments.filter(e=>e.model===model&&e.horizon===1).sort((a,b)=>b.validation.balanced_accuracy-a.validation.balanced_accuracy||a.validation.brier-b.validation.brier)[0]);
 return `<div class="hero-summary"><span class="eyebrow">Measured research · ${r.experiments.length} configurations · ${r.assets.length} assets</span><h3>What does the evidence show?</h3><p>${esc(modelName(s.model))} was selected using development class-balanced accuracy, with Brier score as the tie-breaker. The one-day NIFTY holdout accuracy is ${prob(s.holdout.accuracy)} versus ${prob(s.holdout.majority_accuracy)} for the majority-class benchmark.</p><p class="mt">${esc(r.holdout_warning)}</p></div>
 ${panel('Prediction target & evaluation','Next trading session close-to-close direction; three- and five-session targets are exploratory.',`<p>${esc(r.methodology)}</p><p>Selected inputs: ${esc(s.feature_set.replaceAll('_',' + '))}. Probability calibration: ${s.calibration?'sigmoid':'not selected by development results'}. ${esc(r.news_status)}</p><p>Accuracy is not investment return. Costs, trade timing and signal size also affect historical performance.</p>`)}
 ${panel('Model performance','Each row uses that model’s best development configuration for the primary one-day task. Metrics below are retrospective holdout results.',table(['Model','Inputs',...metricHeaders()],models.map(e=>[modelName(e.model)+(e.configuration===s.configuration&&e.feature_set===s.feature_set?' · selected':''),esc(e.feature_set),...metricCells(e.holdout)])))}
 ${panel('Comparable legacy results','Frozen original artifacts scored on exactly the same dates as the new holdout. Legacy training ended earlier.',r.comparable_legacy?table(['Original model',...metricHeaders()],r.comparable_legacy.map(x=>[modelName(x.model),...metricCells(x.metrics)])):empty('Run the research audit to generate a like-for-like comparison.'))}
 ${panel('Confusion matrix','Rows are actual outcomes; columns are predictions. Counts expose which errors are made.',table(['Actual / predicted','DOWN','UP'],[['DOWN',...s.holdout.confusion_matrix[0]],['UP',...s.holdout.confusion_matrix[1]]])+`<p>Holdout observations: ${s.holdout.n}. ${s.accuracy_block_interval_95?`95% moving-block accuracy interval: ${prob(s.accuracy_block_interval_95[0])}–${prob(s.accuracy_block_interval_95[1])}. Blocks contain 10 sessions.`:''}</p>`)}
 ${panel('Performance by asset','The same configuration is used for every asset, with a separate historical fit per asset.',`<div class="table-tools"><input id="researchAsset" type="search" aria-label="Search asset performance" placeholder="Search symbol"><select id="assetSort" aria-label="Sort performance"><option value="symbol">Symbol A–Z</option><option value="accuracy">Accuracy: high to low</option><option value="f1">F1: high to low</option></select></div><div id="assetPerformance"></div>`)}
 ${panel('Performance by market environment','Pooled predictions grouped by causal GMM states ordered from weaker to stronger historical return. These differ from retrospective descriptive HMM labels.',table(['Causal category','Predictions','Actual UP share','Mean probability',...metricHeaders()],r.environment_performance.map(x=>[`State ${x.state} · ${['weaker','middle','stronger'][x.state]} return profile`,x.n,prob(x.actual_up_fraction),prob(x.mean_probability),...metricCells(x)])))}
 ${panel('Stability across time','Development-fold accuracy varies. Each training label was available before its validation period.',`<div class="chart-wrap short"><canvas id="foldChart"></canvas></div>${table(['Fold','Training label cutoff','Validation period','Accuracy','Class-balanced'],winner.folds.map((f,i)=>[i+1,date(f.label_end),`${date(f.validation_start)} – ${date(f.validation_end)}`,prob(f.accuracy),prob(f.balanced_accuracy)]))}<p>Mean ${prob(winner.validation.fold_accuracy_mean)} · standard deviation ${prob(winner.validation.fold_accuracy_std)}.</p>`)}
 ${panel('Probability reliability','Mean predicted UP probability versus the observed UP frequency, pooled across held-out asset predictions. No claim of calibrated confidence is made.',`<div class="chart-wrap short"><canvas id="calibrationChart"></canvas></div>${table(['Probability range','Predictions','Mean estimate','Observed UP rate'],r.probability_bins.map(b=>[`${Math.round(b.lower*100)}–${Math.round((b.lower+.1)*100)}%`,b.count,prob(b.mean_probability),prob(b.observed_up_rate)]))}`)}
 ${panel('What inputs matter to the model?','Mean absolute SHAP contribution across NIFTY holdout predictions from the frozen evaluation model. Magnitudes describe model dependence, not causation.',table(['Input','Mean |SHAP|'],(r.feature_importance||[]).slice(0,15).map(f=>[esc(prettyFeature(f.feature)),num(f.mean_absolute_shap,5)])))}
 ${panel('Does market context help?','Compare the same selected model across feature sets. Adding context is not assumed to improve performance.',table(['Inputs','Development balanced accuracy','Holdout accuracy','Holdout F1','Holdout separation'],r.experiments.filter(e=>e.horizon===1&&e.configuration===s.configuration&&!e.calibration).map(e=>[esc(e.feature_set),prob(e.validation.balanced_accuracy),prob(e.holdout.accuracy),prob(e.holdout.f1),prob(e.holdout.roc_auc)])))}
 ${panel('Estimated-return research','A separate Ridge regression predicts next-session return. Negative R² means it underperformed the test-mean benchmark.',table(['MAE','RMSE','R²','Zero-return MAE'],[[num(s.holdout.regression.mae,5),num(s.holdout.regression.rmse,5),num(s.holdout.regression.r2,3),num(s.holdout.regression.zero_return_mae,5)]]))}
 <details class="card details mt"><summary>Every experiment, including weaker results</summary>${table(['Horizon','Configuration','Inputs','Calibration','Development balanced',...metricHeaders()],r.experiments.map(e=>[`${e.horizon} sessions`,esc(e.configuration),esc(e.feature_set),e.calibration?'Sigmoid':'None',prob(e.validation.balanced_accuracy),...metricCells(e.holdout)]))}</details>`;
}
export async function hydrateResearch(){
 const r=await get('/research/experiments'),s=r.selected;
 const render=()=>{const search=document.querySelector('#researchAsset').value.toUpperCase(),sort=document.querySelector('#assetSort').value;const rows=r.assets.filter(a=>a.symbol.includes(search)).sort((a,b)=>sort==='symbol'?a.symbol.localeCompare(b.symbol):b.metrics[sort]-a.metrics[sort]);setSafeHTML(document.querySelector('#assetPerformance'),table(['Asset','Holdout period',...metricHeaders()],rows.map(a=>[`<a href="#predictions?symbol=${encodeURIComponent(a.symbol)}">${esc(a.symbol)}</a>`,`${date(a.start)} – ${date(a.end)}`,...metricCells(a.metrics)])))};
 document.querySelector('#researchAsset').addEventListener('input',render);document.querySelector('#assetSort').addEventListener('change',render);render();
 const win=r.experiments.find(e=>e.configuration===s.configuration&&e.feature_set===s.feature_set&&e.horizon===1&&e.calibration===s.calibration);
 lineChart('foldChart',win.folds.map((f,i)=>`Fold ${i+1}`),[{label:'Accuracy (%)',data:win.folds.map(f=>f.accuracy*100)},{label:'Class-balanced (%)',data:win.folds.map(f=>f.balanced_accuracy*100)}]);
 lineChart('calibrationChart',r.probability_bins.map(b=>`${Math.round(b.lower*100)}–${Math.round((b.lower+.1)*100)}%`),[{label:'Mean predicted UP (%)',data:r.probability_bins.map(b=>b.mean_probability*100)},{label:'Actual UP frequency (%)',data:r.probability_bins.map(b=>b.observed_up_rate*100)}]);
}
