export const featureLabels={return_1d:'1-day return',log_return_1d:'1-day price change',return_5d:'5-day return',return_20d:'20-day return',sma_ratio_10:'10-day moving-average relationship',sma_ratio_20:'20-day moving-average relationship',ema_ratio_12:'12-day exponential trend',ma_cross_10_20:'short- versus medium-term trend',rsi_14:'recent momentum (RSI)',macd:'trend momentum (MACD)',momentum_10:'10-day momentum',volatility_20:'recent volatility',atr_14:'average trading range',bb_width_20:'price-range width',volume_change:'trading-volume change',relative_volume_20:'relative trading activity',drawdown_60:'decline from the recent peak',regime_state:'current market environment',sentiment_mean:'recent news tone',news_volume:'news activity',sentiment_momentum:'change in news tone'};
export const modelLabels={logistic_regression:'Logistic Regression',random_forest:'Random Forest',xgboost:'XGBoost'};
export const strategyLabels={buy_hold:'Buy & Hold',sma_cross:'Simple Trend Strategy',ml:'AI Prediction Strategy',regime_aware:'Market-Environment Strategy',hybrid:'AI + Market Environment Strategy'};
export const metricLabels={accuracy:'Accuracy',precision:'Precision',recall:'Recall',f1:'F1 score',roc_auc:'ROC-AUC',cagr:'Annualised growth',sharpe:'Return relative to risk',sortino:'Return relative to harmful volatility',max_drawdown:'Largest historical decline',volatility:'Volatility',profit_factor:'Profit factor'};
export const metricHelp={accuracy:'Share of evaluated predictions that matched the observed direction.',precision:'Of the upward predictions, the share that were correct.',recall:'Of all actual upward movements, the share the model identified.',f1:'Balance between precision and recall.',roc_auc:'How well the model separates upward and downward outcomes across probability thresholds.',sharpe:'Historical return relative to total variability. Higher is better, but past results are not guarantees.',sortino:'Historical return relative only to harmful downside variability.',max_drawdown:'The largest fall from a previous peak during the evaluated period.',profit_factor:'Gross gains divided by gross losses.'};
export const prettyFeature=k=>featureLabels[k]||String(k).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export const regimeName=label=>{if(!label)return 'Market environment unavailable';return String(label).replace(/^State\s+\d+:\s*/i,'').replace(/;.*$/,'').replace(/^./,c=>c.toUpperCase())};
export const regimeMeaning=label=>{const text=String(label||'').replace(/^State\s+\d+:\s*/i,'').replaceAll(';',',');return text?`Recent price behaviour is characterised as ${text}. This is a description of observed conditions, not a forecast.`:'There is not enough persisted regime information to describe the current market environment.'};
export function movementText(change){if(change==null)return 'Change unavailable';const n=Math.abs(change);if(n<0.002)return 'Little changed in the latest session';if(change>0)return n<0.01?'Slightly higher in the latest session':'Higher in the latest session';return n<0.01?'Slightly lower in the latest session':'Lower in the latest session'}
export function signalSummary(feature={}){const rsi=feature.rsi_14,macd=feature.macd,vol=feature.volatility_20,rv=feature.relative_volume_20,cross=feature.ma_cross_10_20;return {momentum:rsi==null?'Unavailable':rsi>60?'Positive':rsi<40?'Negative':'Neutral',trend:cross==null&&macd==null?'Unavailable':(cross||0)>0&&(macd||0)>0?'Upward':(cross||0)<0&&(macd||0)<0?'Downward':'Mixed',volatility:vol==null?'Unavailable':vol<.012?'Low':vol>.025?'High':'Moderate',activity:rv==null?'Unavailable':rv>1.25?'Above average':rv<.75?'Below average':'Normal'}}
export const influenceText=(key,value)=>`${prettyFeature(key)} ${value>=0?'supported':'weighed against'} the upward-movement estimate.`;
