export const featureLabels={return_1d:'1-day return',return_2d:'2-day return',return_3d:'3-day return',return_5d:'5-day return',return_10d:'10-day return',return_20d:'20-day return',log_return:'log return',log_return_1d:'1-day price change',return_acceleration:'return acceleration',sma_5:'5-day moving average',sma_10:'10-day moving average',sma_20:'20-day moving average',sma_50:'50-day moving average',ema_10:'10-day exponential average',ema_20:'20-day exponential average',ema_50:'50-day exponential average',price_to_sma20:'price relative to 20-day trend',price_to_sma50:'price relative to 50-day trend',trend_strength:'trend strength',sma_ratio_5:'5-day moving-average relationship',sma_ratio_10:'10-day moving-average relationship',sma_ratio_20:'20-day moving-average relationship',sma_ratio_50:'50-day moving-average relationship',sma_ratio_100:'100-day moving-average relationship',ema_ratio_5:'5-day exponential trend',ema_ratio_10:'10-day exponential trend',ema_ratio_20:'20-day exponential trend',ema_ratio_50:'50-day exponential trend',ma_cross_10_20:'short- versus medium-term trend',rsi_14:'recent momentum (RSI)',rsi_change_5:'five-day RSI change',macd:'trend momentum (MACD)',macd_signal:'MACD signal',macd_hist:'MACD momentum gap',macd_histogram:'MACD momentum gap',momentum_5d:'5-day momentum',momentum_10:'10-day momentum',roc_10:'10-day rate of change',stochastic_14:'stochastic momentum',rolling_volatility_20:'20-day annualised volatility',volatility_20:'recent volatility',volatility_ratio_20:'volatility relative to its recent level',atr_14:'average trading range',atr_percentage:'average trading range as a share of price',bb_width_20:'price-range width',bollinger_width:'Bollinger-band width',volume_change:'trading-volume change',volume_sma_20:'20-day average volume',volume_z_20:'volume unusualness',volume_zscore:'volume unusualness',relative_volume:'relative trading activity',relative_volume_20:'relative trading activity',price_volume_interaction:'price-volume interaction',market_return:'broad-market return',market_momentum:'broad-market momentum',market_volatility:'broad-market volatility',sector_return:'sector return',sector_momentum:'sector momentum',market_environment_code:'market environment',regime_duration:'environment duration',regime_strength:'environment strength',volatility_regime_code:'volatility environment',intraday_return:'open-to-close return',overnight_return:'previous-close-to-open return',drawdown_60:'decline from the recent peak',relative_strength_nifty:'performance versus NIFTY 50',regime_state:'current market environment',sentiment_mean:'recent news tone',news_volume:'news activity',sentiment_momentum:'change in news tone'};
export const modelLabels={logistic_regression:'Logistic Regression',random_forest:'Random Forest',xgboost:'XGBoost'};
export const strategyLabels={buy_hold:'Buy & Hold',sma_cross:'Simple Trend Strategy',ml:'AI Prediction Strategy',regime_aware:'Market-Environment Strategy',hybrid:'AI + Market Environment Strategy'};
export const metricLabels={accuracy:'Accuracy',precision:'Precision',recall:'Recall',f1:'F1 score',roc_auc:'ROC-AUC',cagr:'Annualised growth',sharpe:'Return relative to risk',sortino:'Return relative to harmful volatility',max_drawdown:'Largest historical decline',volatility:'Volatility',profit_factor:'Profit factor'};
export const metricHelp={accuracy:'Share of evaluated predictions that matched the observed direction.',precision:'Of the upward predictions, the share that were correct.',recall:'Of all actual upward movements, the share the model identified.',f1:'Balance between precision and recall.',roc_auc:'How well the model separates upward and downward outcomes across probability thresholds.',sharpe:'Historical return relative to total variability. Higher is better, but past results are not guarantees.',sortino:'Historical return relative only to harmful downside variability.',max_drawdown:'The largest fall from a previous peak during the evaluated period.',profit_factor:'Gross gains divided by gross losses.'};
export const prettyFeature=k=>featureLabels[k]||String(k).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export const regimeName=label=>{if(!label)return 'Market environment unavailable';return String(label).replace(/^State\s+\d+:\s*/i,'').replace(/;.*$/,'').replace(/^./,c=>c.toUpperCase())};
export const regimeMeaning=label=>{const text=String(label||'').replace(/^State\s+\d+:\s*/i,'').replaceAll(';',',');return text?`Recent price behaviour is characterised as ${text}. This is a description of observed conditions, not a forecast.`:'There is not enough persisted regime information to describe the current market environment.'};
export function movementText(change){if(change==null)return 'Change unavailable';const n=Math.abs(change);if(n<0.002)return 'Little changed in the latest session';if(change>0)return n<0.01?'Slightly higher in the latest session':'Higher in the latest session';return n<0.01?'Slightly lower in the latest session':'Lower in the latest session'}
export function signalSummary(feature={}){const rsi=feature.rsi_14,macd=feature.macd,vol=feature.volatility_20,rv=feature.relative_volume_20,cross=feature.ma_cross_10_20;return {momentum:rsi==null?'Unavailable':rsi>60?'Positive':rsi<40?'Negative':'Neutral',trend:cross==null&&macd==null?'Unavailable':(cross||0)>0&&(macd||0)>0?'Upward':(cross||0)<0&&(macd||0)<0?'Downward':'Mixed',volatility:vol==null?'Unavailable':vol<.12?'Low':vol>.20?'High':'Moderate',activity:rv==null?'Unavailable':rv>1.25?'Above average':rv<.75?'Below average':'Normal'}}
export const influenceText=(key,value)=>`${prettyFeature(key)} ${value>=0?'supported':'weighed against'} the upward-movement estimate.`;
